# Generated by Django 4.2.13 on 2024-06-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='test',
            new_name='text',
        ),
    ]
